[build]
publish = "dist"
command = "npx vite build"

[build.environment]
SECRETS_SCAN_OMIT_KEYS = "SUPABASE_ANON_KEY,SUPABASE_URL,VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_URL"

[functions]
directory = "api"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200